services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - PAMPS_DB=pamps
      - PAMPS_DB_URI="postgresql://postgres:postgres@db:5432/${PAMPS_DB:-pamps}"
      - PAMPS_DB_connect_args={}
    volumes:
      - .:/home/app/api
      - ./pamps:/home/mariobarc/projetoFast/pamps
    depends_on:
      - db
  db:
    build: postgres
    image: pamps_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/pamps_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DBS=pamps, pamps_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres